### ISSUE TITLE
what the project is about?

### ISSUE THREAD

**Issue by killpanda** [yao23/FollowMe#1]

**Comment by yao23** [comment]
A game in a Swift tutorial book, what are you working now? Frontend, backend or mobile development?

**Comment by killpanda** [comment]
backend web development. Im currently in Beijing, in a small startup company.

**Comment by yao23** [comment]
any link about your company? do you enjoy the work?

**Comment by killpanda** [comment]
www.vipkid.com.cn  busy busy  busy 百废待兴

**Comment by yao23** [comment]
how about the tech stack?

**Comment by killpanda** [comment]
Use Java mainly...

**Comment by killpanda** [comment]
This company is marketing-driven. Cofounder came from traditional software industry, so everything is written by Java.

**Comment by yao23** [comment]
How about the business running? Is it going well, expand widely? How do you support the company, investment or own revenue?

**Comment by killpanda** [comment]
It's running well.

> How do you support the company
> ?

**Comment by killpanda** [comment]
pls close this issue
